<?php

/**
 * Generated by PHPUnit_SkeletonGenerator.
 * @author HLO & Boeck
 * REMINDER! Remember comment out session_start() in top of Config.php
 * Some of the preceeding method calls use Config.php, and the test will
 * FAIL because of some session issues.
 */
class User_controllerTest extends PHPUnit_Framework_TestCase {

    /**
     * @var User_controller
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     * @session_start();
     */
    protected function setUp() {
        $this->object = new User_controller;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers User_controller::generate_salt
     * @todo   
     * @runInSeparateProcess
     */
    public function testSaltLenghtIsNotBetweenZeroAndNineteen() {
        $salt = $this->object->generate_salt();
        $this->assertGreaterThan(19, strlen($salt));
    }

    /**
     * @covers User_controller::generate_salt
     * @todo   
     * @runInSeparateProcess
     */
    public function testSaltLenghtIsNotAboveThirty() {
        $salt = $this->object->generate_salt();
        $this->assertLessThan(31, strlen($salt));
    }

    /**
     * @covers User_controller::validate_email
     * @todo   Implement testValidate_email().
     */
    public function testValidateValidEmail() {
        $email = $this->object->validate_email("heini.ovason_1@gmail.com");
        $this->assertTrue($email);
    }

    /**
     * @covers User_controller::validate_email
     * @todo   Implement testValidate_email().
     */
    public function testValidateInvalidEmail() {
        $email = $this->object->validate_email("heini.ovason_1");
        $this->assertFalse($email);
    }

    /**
     * @covers User_controller::validate_email
     * @todo   Implement testValidate_email().
     */
    public function testValidateRegisteredEmail() {
        $email = $this->object->validate_email("heini.ovason@gmail.com");
        $this->assertFalse($email);
    }

}
